steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg',
      'VITE_API_URL=${_API_URL}',
      '-t',
      'gcr.io/$PROJECT_ID/futuris-frontend',
      '.'
    ]
    dir: 'frontend'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/futuris-frontend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'futuris-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/futuris-frontend'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/futuris-frontend'

substitutions:
  _API_URL: 'https://futuris-2-0-242775953468.asia-south1.run.app'

options:
  logging: CLOUD_LOGGING_ONLY
